package com.example.demo;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;

@Controller // This means that this class is a Controller
@RequestMapping(path="/demo") // This means URL's start with /demo (after Application path)
public class CourseController {
    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private CourseRepository courseRepository;

    @PostMapping(path="course/add") // Map ONLY POST Requests
    public @ResponseBody String addNewCourse (@RequestParam String course_name, @RequestParam String dept_name
            , @RequestParam Integer instructor_id, @RequestParam Integer duration) {
        // @ResponseBody means the returned String is the response, not a view name
        // @RequestParam means it is a parameter from the GET or POST request
        Course n = new Course();
        n.setCourseName(course_name);
        n.setDeptName(dept_name);
        n.setInstructorID(instructor_id);
        n.setDuration(duration);
        courseRepository.save(n);
        return "Course Added Successfully";
    }

    @GetMapping(path="course/all")
    public @ResponseBody Iterable<Course> getAllCourses() {
        // This returns a JSON or XML with the users
        return courseRepository.findAll();
    }
}

